version: '3.6'

services:
  web:
    container_name: fr_test
    build: ./app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.dev.env
    networks:
      - ft_bridge

  db:
    container_name: ft_db
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.dev.env
    networks:
      - ft_bridge


networks:
  ft_bridge:
    driver: bridge
