version: '3.6'

services:
  web:
    container_name: fr_test
    build: ./app
    restart: always
    command: bash start.sh
    volumes:
      - ./app:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.dev.env
    networks:
      - ft_bridge

  db:
    container_name: ft_db
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.dev.env
    networks:
      - ft_bridge

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    container_name: ft_rabbitmq
    hostname: fab
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.dev.env
    volumes:
      - ./rabbit/data/:/var/lib/rabbitmq/
      - ./rabbit/log/:/var/log/rabbitmq
    networks:
      - ft_bridge


networks:
  ft_bridge:
    driver: bridge
