# Generated by Django 4.1.4 on 2022-12-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(help_text='номер телефона в формате 7XXXXXXXXXX (X - цифра от 0 до 9)', max_length=11, unique=True, verbose_name='номер телефона'),
        ),
    ]
